language: go

go:
  - "1.7"
  - "1.9"
  - "1.10"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libnetfilter-log-dev libnetfilter-queue-dev
  - sudo curl -o /usr/lib/libnavl.so http://foo:foo@updates.untangle.com/public/openwrt/libnavl.so.4.5.0
  - sudo ldconfig
  - ldd /usr/lib/libnavl.so

script:
  - true
