language: go

go:
  - "1.9"

env:
  - LDFLAGS=-ldl

before_install:
  - echo "deb http://foo:foo@updates.untangle.com/public/stretch 14.0.0 main non-free" | sudo tee -a /etc/apt/sources.list
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 735A9E18E8F62EDF413592460B9D6AE3627BF103
  - sudo apt-get update -qq
  - sudo apt-get install -y libnetfilter-log-dev libnetfilter-queue-dev libstdc++6
  - sudo curl -o /usr/lib/libnavl.so http://foo:foo@updates.untangle.com/public/openwrt/libnavl.so.4.5.0
  - sudo ldconfig
  - ldd /usr/lib/libnavl.so

script:
  - true
