language: go

before_install:
  - echo "deb http://updates.untangle.com/public/stretch 14.0.0 main non-free" | sudo tee -a /etc/apt/sources.list
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 735A9E18E8F62EDF413592460B9D6AE3627BF103
  - sudo apt-get update -qq
  - sudo apt-get install -y untangle-classd libnetfilter-log-dev libnetfilter-queue-dev

install:
  - go get
  - go build
